apiVersion: v1
kind: ResourceQuota
metadata:
  name: mlops-platform-quota
  namespace: mlops-platform
spec:
  hard:
    # Compute resources
    requests.cpu: "10"
    requests.memory: "20Gi"
    limits.cpu: "20"
    limits.memory: "40Gi"
    
    # Storage
    requests.storage: "100Gi"
    persistentvolumeclaims: "10"
    
    # Objects
    pods: "50"
    services: "20"
    configmaps: "20"
    secrets: "20"
    replicationcontrollers: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mlops-platform-limits
  namespace: mlops-platform
spec:
  limits:
    # Container limits
    - type: Container
      max:
        cpu: "4"
        memory: "8Gi"
      min:
        cpu: "100m"
        memory: "128Mi"
      default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "250m"
        memory: "256Mi"
    
    # Pod limits
    - type: Pod
      max:
        cpu: "8"
        memory: "16Gi"
    
    # PVC limits
    - type: PersistentVolumeClaim
      max:
        storage: "50Gi"
      min:
        storage: "1Gi"
