apiVersion: v1
kind: Service
metadata:
  name: mlflow-server
  namespace: mlops-platform
  labels:
    app: mlflow-server
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: mlflow-server
